/* tslint:disable */
/* eslint-disable */
/**
 * Servicio de Normalización de Datos Geográficos de Argentina
 * Permite normalizar y codificar los nombres de unidades territoriales de la Argentina (provincias, departamentos, municipios y localidades) y de sus calles, así como ubicar coordenadas dentro de ellas.
 *
 * The version of the OpenAPI document: 0.5.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { InlineObject } from '../models';
/**
 * DatosgeoApi - axios parameter creator
 * @export
 */
export const DatosgeoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {InlineObject} [inlineObject] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        obtenerLocalidadesPorLote: async (inlineObject?: InlineObject, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/localidades`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(inlineObject, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DatosgeoApi - functional programming interface
 * @export
 */
export const DatosgeoApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DatosgeoApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {InlineObject} [inlineObject] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async obtenerLocalidadesPorLote(inlineObject?: InlineObject, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.obtenerLocalidadesPorLote(inlineObject, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DatosgeoApi - factory interface
 * @export
 */
export const DatosgeoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DatosgeoApiFp(configuration)
    return {
        /**
         * 
         * @param {InlineObject} [inlineObject] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        obtenerLocalidadesPorLote(inlineObject?: InlineObject, options?: any): AxiosPromise<object> {
            return localVarFp.obtenerLocalidadesPorLote(inlineObject, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for obtenerLocalidadesPorLote operation in DatosgeoApi.
 * @export
 * @interface DatosgeoApiObtenerLocalidadesPorLoteRequest
 */
export interface DatosgeoApiObtenerLocalidadesPorLoteRequest {
    /**
     * 
     * @type {InlineObject}
     * @memberof DatosgeoApiObtenerLocalidadesPorLote
     */
    readonly inlineObject?: InlineObject
}

/**
 * DatosgeoApi - object-oriented interface
 * @export
 * @class DatosgeoApi
 * @extends {BaseAPI}
 */
export class DatosgeoApi extends BaseAPI {
    /**
     * 
     * @param {DatosgeoApiObtenerLocalidadesPorLoteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DatosgeoApi
     */
    public obtenerLocalidadesPorLote(requestParameters: DatosgeoApiObtenerLocalidadesPorLoteRequest = {}, options?: AxiosRequestConfig) {
        return DatosgeoApiFp(this.configuration).obtenerLocalidadesPorLote(requestParameters.inlineObject, options).then((request) => request(this.axios, this.basePath));
    }
}
