/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * Servidor Express
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse2002RoleAssignments
 */
export interface InlineResponse2002RoleAssignments {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2002RoleAssignments
     */
    'projectId'?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002RoleAssignments
     */
    'role'?: string;
}

