version: '3'
services:
  cube:
    environment:
      - CUBEJS_CUBESTORE_HOST=localhost
      - CUBEJS_REDIS_URL=redis://redis:6379
    depends_on:
      - cubestore
    links:
      - cubestore
  cubestore:
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_REMOTE_DIR=/cube/data
    volumes:
      - ./deploy/cubestore/data:/cube/data
  frontend:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./deploy/production/.nginx/nginx.conf:/etc/nginx/nginx.conf
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    logging:
      driver: none
