version: '3'
services:
  cube:
    image: cubejs/cube:v0.30.64
    container_name: cube-dashboard
    ports:
      - 4040:4000
      - 3030:3000
    environment:
      - CUBEJS_DB_HOST=${PG_HOST}
      - CUBEJS_DB_NAME=${PG_DBNAME}
      - CUBEJS_DB_USER=${PG_USER}
      - CUBEJS_DB_PASS=${PG_PASSWORD}
      - CUBEJS_DB_PORT=${PG_PORT}
      - CUBEJS_WEB_SOCKETS=true
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_TYPE=postgres
      - CUBEJS_API_SECRET=${CUBE_SECRET}
    env_file: .env
    volumes:
      - ./cubejs/:/cube/conf
  backend:
    build:
      context: ./backend
    container_name: backend-arphai
    ports:
      - 5000:5000
    env_file: ./backend/.env
    volumes:
      - ./backend/app.js:/app/app.js
