/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { InlineObject } from '../models';
// @ts-ignore
import { InlineResponse2001 } from '../models';
// @ts-ignore
import { InlineResponse4001 } from '../models';
/**
 * RefreshApi - axios parameter creator
 * @export
 */
export const RefreshApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {InlineObject} [inlineObject] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refreshToken: async (inlineObject?: InlineObject, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(inlineObject, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RefreshApi - functional programming interface
 * @export
 */
export const RefreshApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RefreshApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {InlineObject} [inlineObject] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async refreshToken(inlineObject?: InlineObject, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2001>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.refreshToken(inlineObject, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * RefreshApi - factory interface
 * @export
 */
export const RefreshApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RefreshApiFp(configuration)
    return {
        /**
         * 
         * @param {InlineObject} [inlineObject] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refreshToken(inlineObject?: InlineObject, options?: any): AxiosPromise<InlineResponse2001> {
            return localVarFp.refreshToken(inlineObject, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for refreshToken operation in RefreshApi.
 * @export
 * @interface RefreshApiRefreshTokenRequest
 */
export interface RefreshApiRefreshTokenRequest {
    /**
     * 
     * @type {InlineObject}
     * @memberof RefreshApiRefreshToken
     */
    readonly inlineObject?: InlineObject
}

/**
 * RefreshApi - object-oriented interface
 * @export
 * @class RefreshApi
 * @extends {BaseAPI}
 */
export class RefreshApi extends BaseAPI {
    /**
     * 
     * @param {RefreshApiRefreshTokenRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RefreshApi
     */
    public refreshToken(requestParameters: RefreshApiRefreshTokenRequest = {}, options?: AxiosRequestConfig) {
        return RefreshApiFp(this.configuration).refreshToken(requestParameters.inlineObject, options).then((request) => request(this.axios, this.basePath));
    }
}
