SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE TABLE tableros.snvs (
	ideventocaso varchar(255) NULL,
	evento varchar(255) NULL,
	nombre varchar(255) NULL,
	apellido varchar(255) NULL,
	tipo_doc varchar(255) NULL,
	nro_doc varchar(255) NULL,
	sexo varchar(255) NULL,
	pais_residencia varchar(255) NULL,
	departamento_residencia varchar(255) NULL,
	provincia_carga varchar(255) NULL,
	localidad_carga varchar(255) NULL,
	establecimiento_carga varchar(255) NULL,
	signo_sintoma varchar(255) NULL,
	fis varchar(255) NULL,
	min_ftm varchar(255) NULL,
	fecha_apertura varchar(255) NULL,
	internado varchar(255) NULL,
	curado varchar(255) NULL,
	cuidado_intensivo varchar(255) NULL,
	fallecido varchar(255) NULL,
	asist_resp_mecanica varchar(255) NULL,
	id_provincia_residencia varchar(255) NULL,
	id_provincia_carga varchar(255) NULL,
	origen_financiamiento varchar(255) NULL,
	estab_diagnostico varchar(1000) NULL,
	clasif_resumen varchar(255) NULL,
	clasif_epidemio varchar(255) NULL,
	codigo_refes_estab_carga varchar(255) NULL,
	fecha_grafico varchar(255) NULL,
	grupo_etario_decada varchar(255) NULL,
	cobertura_social varchar(255) NULL,
	malbran varchar(255) NULL,
	id_depto_indec_residencia varchar(255) NULL,
	id_depto_indec_carga varchar(255) NULL,
	asma varchar(255) NULL,
	bajo_peso varchar(255) NULL,
	bronquio_previa varchar(255) NULL,
	dbt varchar(255) NULL,
	embarazo varchar(255) NULL,
	enf_neuro_previa varchar(255) NULL,
	enf_onco_previa varchar(255) NULL,
	epoc varchar(255) NULL,
	hepato_cronica varchar(255) NULL,
	hta varchar(255) NULL,
	inmunos_congenita varchar(255) NULL,
	insf_cardiaca varchar(255) NULL,
	insf_renal varchar(255) NULL,
	nac_previa varchar(255) NULL,
	obesidad varchar(255) NULL,
	prematuro varchar(255) NULL,
	sin_comorb varchar(255) NULL,
	tbc varchar(255) NULL,
	ex_fumador varchar(255) NULL,
	fumador varchar(255) NULL,
	tratamiento_fecha_resultado varchar(255) NULL,
	id_provincia_indec varchar(255) NULL,
	estab_diag_no_malbran varchar(255) NULL,
	estab_internacion varchar(255) NULL,
	codigo_refes_estab_internacion varchar(255) NULL,
	fecha_mod_evento varchar(255) NULL,
	fecha_mod_diag varchar(255) NULL,
	fecha_internacion varchar(255) NULL,
	fecha_cui_intensivos varchar(255) NULL,
	fecha_fallecimiento varchar(255) NULL,
	fecha_alta_medica varchar(255) NULL,
	observaciones varchar(1000) NULL,
	calle_domicilio varchar(255) NULL,
	id_localidad_residencia varchar(255) NULL,
	localidad_residencia varchar(255) NULL,
	numero_domicilio varchar(255) NULL,
	provincia_residencia varchar(255) NULL,
	edad_actual varchar(255) NULL,
	info_contacto varchar(255) NULL,
	clasificacion varchar(255) NULL,
	fecha_mod_clasif varchar(255) NULL,
	estado_paciente varchar(30) NULL,
	fecha_mod_estadopaciente varchar(30) NULL,
	tipo_movimiento varchar(1) NULL,
	fecha_diagnostico varchar(30) NULL,
	fecha_nacimiento varchar(30) NULL,
	fecha_alta timestamp NULL,
	ws_alta varchar(50) NULL,
	fecha_modif timestamp NULL,
	ws_modif varchar(50) NULL,
	fuente varchar(3) NULL,
	fecha_fallecimiento_upd varchar(50) NULL
); 

ALTER TABLE tableros.snvs OWNER TO dashboarduser;

