/* tslint:disable */
/* eslint-disable */
/**
 * Servicio de Normalización de Datos Geográficos de Argentina
 * Permite normalizar y codificar los nombres de unidades territoriales de la Argentina (provincias, departamentos, municipios y localidades) y de sus calles, así como ubicar coordenadas dentro de ellas.
 *
 * The version of the OpenAPI document: 0.5.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/datosgeo-api';

