/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { InlineResponse200User } from './inline-response200-user';

/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {InlineResponse200User}
     * @memberof InlineResponse200
     */
    'user'?: InlineResponse200User;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    'accessToken'?: string;
}

