/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse200User
 */
export interface InlineResponse200User {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200User
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200User
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200User
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200User
     */
    'email'?: string;
}

