/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineObject1
 */
export interface InlineObject1 {
    /**
     * 
     * @type {string}
     * @memberof InlineObject1
     */
    'token'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject1
     */
    'refresh'?: string;
}

