/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse4001
 */
export interface InlineResponse4001 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse4001
     */
    'error'?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse4001
     */
    'code'?: number;
}

