/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse2002
 */
export interface InlineResponse2002 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002
     */
    'about'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002
     */
    'company'?: string;
}

