/* tslint:disable */
/* eslint-disable */
/**
 * Account API
 * Account API description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { InlineResponse200RoleAssignments } from './inline-response200-role-assignments';

/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {Array<InlineResponse200RoleAssignments>}
     * @memberof InlineResponse200
     */
    'roleAssignments'?: Array<InlineResponse200RoleAssignments>;
}

