/* tslint:disable */
/* eslint-disable */
/**
 * Account API
 * Account API description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse200RoleAssignments
 */
export interface InlineResponse200RoleAssignments {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200RoleAssignments
     */
    'projectId'?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200RoleAssignments
     */
    'role'?: string;
}

