openapi: 3.0.3
info:
  title: Backend API
  description: 'Servidor Express'
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /auth:
    post:
      operationId: loginUser
      tags:
        - backend
        - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      firstName:
                        type: string
                      lastName:
                        type: string
                      email:
                        type: string
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
        400:
          description: Credenciales Inválidas
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /auth/refresh:
    post:
      operationId: refreshToken
      tags:
        - backend
        - refresh
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshToken'
      responses:
        '200':
          description: succesful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      firstName:
                        type: string
                      lastName:
                        type: string
                      email:
                        type: string
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
                  code:
                    type: number
        '400':
          description: Bad Request
        '401':
          description: Sesión expirada
  /hsi/account/permissions:
    get:
      operationId: getHsiAccountPermissions
      tags:
        - backend
        - account
        - permissions
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  roleAssignments:
                    type: array
                    items:
                      type: object
                      properties:
                        projectId:
                          type: number
                        role:
                          type: string
        '400':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /hsi/account/info:
    get:
      operationId: getHsiAccountInfo
      tags:
        - backend
        - account
        - info
      responses:
        '200':
          description: succesful
          content:
            application/json:
              schema:
                type: object
                properties:
                  info:
                    type: string
        '401':
          description: Unauthorized
  /hsi/public/version:
    get:
      operationId: getHsiPublicVersion
      tags:
        - backend
        - public
        - version
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
        '400':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /hsi/public/info:
    get:
      operationId: getHsiPublicInfo
      tags:
        - backend
        - public
        - info
      responses:
        '200':
          description: succesful
          content:
            application/json:
              schema:
                type: object
                properties:
                  flavor:
                    type: string
        '401':
          description: Unauthorized
  /public/version:
    get:
      operationId: getPublicVersion
      tags:
        - backend
        - public
        - version
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
        '400':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
    RefreshToken:
      type: object
      properties:
        refreshToken:
          type: string
    LoginUser:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
