openapi: 3.0.3
info:
  title: Account API
  description: 'Account API description'
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /account/permissions:
    get:
      operationId: getAccountPermissions
      tags:
        - account
        - permissions
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  roleAssignments:
                    type: array
                    items:
                      type: object
                      properties:
                        projectId:
                          type: number
                        role:
                          type: string
        '400':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /account/info:
    get:
      operationId: getAccountInfo
      tags:
        - account
        - info
      responses:
        '200':
          description: succesful
          content:
            application/json:
              schema:
                type: object
                properties:
                  info:
                    type: string
        '401':
          description: Unauthorized