/* tslint:disable */
/* eslint-disable */
/**
 * Nominatim
 * Interface for the search engine used on the OpenStreetMap website
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/osm-api';

